# -*- coding: utf-8 -*-
"""Wav2Lip_quick_trial_fixed.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iNYxaWWzkESw_snfyyOTcLp6CTiW5nN0

Modified version of the Wav2Lip_quick_trial notebook to work directly in the Drive folder, and fix a naming issue

# Collab preliminaries
"""

from google.colab import drive
drive.mount('/content/gdrive')

"""# Get the code and models"""

!git clone https://github.com/Rudrabha/Wav2Lip.git "/content/gdrive/My Drive/Wav2Lip"

"""Here, you need to download the wav2lip.gan.pth file and place it in your Wav2Lip/checkpoints/ folder in Drive.

Link: https://iiitaphyd-my.sharepoint.com/:u:/g/personal/radrabha_m_research_iiit_ac_in/EdjI7bZlgApMqsVoEUUXpLsBxqXbn5z8VTmoxp55YNDcIA?e=n9ljGW

# Get the pre-requisites
"""

!pip uninstall tensorflow tensorflow-gpu

!cd "/content/gdrive/My Drive/Wav2Lip/" && pip install -r requirements.txt

!wget "https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth" -O "/content/gdrive/My Drive/Wav2Lip/face_detection/detection/sfd/s3fd.pth"

"""# Now lets try!

Put some audio and video files in your Wav2Lip folder (modify command below with their names).
"""

!cd "/content/gdrive/My Drive/Wav2Lip" && python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth --face "input_vid.mp4" --audio "input_audio.wav"

!ls "/content/gdrive/My Drive/Wav2Lip/results/"

# Result is now in your Drive Wav2Lip/results/ folder.

"""## **Variations to try**

1.   Use more padding to include the chin region
"""

!cd Wav2Lip && python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth --face "../sample_data/input_vid.mp4" --audio "../sample_data/input_audio.wav" --pads 0 20 0 0

"""2.   Use resize_factor to reduce the video resolution, as there is a change you might get better results for lower resolution videos. Why? Because the model was trained on low resolution faces."""

!cd Wav2Lip && python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth --face "../sample_data/input_vid.mp4" --audio "../sample_data/input_audio.wav" --resize_factor 2